### ISSUE TITLE
Undefined returned from homedir() call passed unto path.join at top level

### ISSUE THREAD

**Issue by whizyrel** [giper45/docker-js#7]
My issue exactly: I am using this module on a NodeJS Server and I get this error
`
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1039:7)
    at eval (webpack://mms-frontend-service/./node_modules/mydockerjs/lib/utils.js?:14:26)
`
I am using this on Linux so, I maybe understand why this happened on this [line](https://github.com/whizyrel/docker-js/blob/1846955177d4a79f13760295667a6f7ae610361a/lib/utils.js#L13). Please check this out, also I would submit a PR of the fix for the sake of linux users.

**Comment by giper45** [comment]
Hi @whizyrel , could you give me more information about the nodejs version , homedir version and used operating system when the issue occurred? Which user is running the code? If you understand the issue, could you give me more details please ? Thank you

**Comment by whizyrel** [comment]
Nodejs: 14.16.0
Homedir: 0.6.0
OS: linux 20.04 LTS
user: non-root user

Thank you for your quick response.
Like I said I am running a NodeJS server where I am using this module. I get that TypeError because `homedir()` returns undefined like so ```path.join(homedir(), ...)``` on [line 13](https://github.com/giper45/docker-js/blob/1846955177d4a79f13760295667a6f7ae610361a/lib/utils.js#L13). It also seem like a issue from `homedir()` since it is supposed to return the user home path on LInux and Windows.

**Comment by giper45** [comment]
Ok, I think that this is related with an external library, homedir. 
https://github.com/wilmoore/node-homedir/blob/master/index.js
If you look at the code, the module tries to get home path by using HOME environment variable:
![image](https://user-images.githubusercontent.com/18548727/115949953-abf84d80-a4d8-11eb-9179-d1bd6d98dbee.png)


Could you check if your username has env HOME defined? 
`echo $HOME`

**Comment by giper45** [comment]
In any case, this is related with toolboxPath, a variable that I never use in the code, as I was trying to implement windows docker toolbox support, but I unfortunately did not have too much time to implement it :-). As it is used for Windows purposes, we can check if the process platform is win32 and use it only if it is the case.

**Comment by giper45** [comment]
If you are able to pull request me this fix, I really appreciate it. Thank you

**Comment by whizyrel** [comment]
Yes, I mentioned it seem like a homedir bug caused it, and it does have a $HOME defined.
I figured process.env['HOME'] does return the path when it is not running as a server otherwise it returns undefined.
While it seem like a `homedir` issue, it actually is not.
So, I use webpack and did not include all of the env vars completely only those I defined.
To solve this issue when someone else does the same thing I did, I could PR. Also, an example of including all env vars in webpack config would be using `EnvironmentPlugin` and not `DefinePlugin` which is a popular choice
[An example Webpack issue](https://github.com/webpack/webpack-cli/issues/2362)

```js
...
plugins: [
   new webpack.EnvironmentPlugin([...Object.keys(process.env)])
]
...
```

Let me know what you think
